title: SJH blog
author: jinhosoon
email: jinho7329@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: true  # set to true to show excerpts on the homepage
baseurl: /sjhow.github.io
remote_theme: samarsault/texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: 백엔드 개발자를 꿈꾸는 순진호 입니다.
  tagline: Web Developer.
  date_format: "%b %-d, %Y"
  style: red
  showNav: true
  showPicker: false
  analytics_id: 'jinho7329@gmail.com'

  # generate social links in footer
  social_links:
    twitter:
    github: jinhosoon
    linkedIn:
    rss: rss
 
theme: texture

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
